[profile.default]
src = 'packages/mycontracts/src'

[doc]
repository = "https://github.com/nitininhouse/forge-doc-test"
repository-path = "packages/mycontracts"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
